//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "User Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "User Name")]
        [DataType(DataType.Text)]
        [StringLength(20, ErrorMessage = "Name can not be more than 20 Characters!")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Contact No")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(15, ErrorMessage = "Max 15 Characters are allowed")]
        [MinLength(6, ErrorMessage = "Min 6 Characters are required")]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "User's Address")]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Message")]
        [DataType(DataType.MultilineText)]
        public string Message { get; set; }
    }
}
