//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sender()
        {
            this.Branches = new HashSet<Branch>();
            this.Dealerships = new HashSet<Dealership>();
            this.Dispatchers = new HashSet<Dispatcher>();
        }

        public int Sender_Id { get; set; }

        [Required]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Sender_Email { get; set; }

        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MaxLength(20, ErrorMessage = "Max 20 Characters are allowed")]
        [MinLength(6, ErrorMessage = "Min 6 Characters are required")]
        public string Sender_Password { get; set; }

        [Required]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Sender_Password", ErrorMessage = "Password and Confirm Password does not match!")]
        public string Confirm_Sender_Password { get; set; }

        [Required]
        [Display(Name = "Contact No")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(15, ErrorMessage = "Max 15 Characters are allowed")]
        [MinLength(6, ErrorMessage = "Min 6 Characters are required")]
        public string Sender_Phone { get; set; }

        [Required]
        [Display(Name = "Sender's Name")]
        [DataType(DataType.Text)]
        [StringLength(20, ErrorMessage = "Name can not be more than 20 Characters!")]
        public string Sender_Name { get; set; }

        [Required]
        [Display(Name = "Sender's Address")]
        [DataType(DataType.MultilineText)]
        public string Sender_Address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealership> Dealerships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispatcher> Dispatchers { get; set; }
    }
}
