//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPage
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Profession { get; set; }
        public string Roll { get; set; }
        public string Section { get; set; }
        public string Group { get; set; }
        public string NickName { get; set; }
        public string fb { get; set; }
        public string gmail { get; set; }
    }
}
